version: '3.8'

services:
  # FastAPI Application
  app:
    build: .
    container_name: slotbazaar_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Running migrations...' &&
        alembic upgrade head &&
        echo 'Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  # Development setup with local PostgreSQL (optional)
  app-dev:
    build: .
    container_name: slotbazaar_app_dev
    environment:
      - DATABASE_URL=postgresql://slotbazaar_user:slotbazaar_password@db:5432/slotbazaar
      - JWT_SECRET_KEY=dev-secret-key
      - DEBUG=True
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python -c 'import time; time.sleep(5)' &&
        echo 'Running migrations...' &&
        alembic upgrade head &&
        echo 'Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    profiles:
      - dev

  # Local PostgreSQL for development
  db:
    image: postgres:15-alpine
    container_name: slotbazaar_db
    environment:
      POSTGRES_DB: slotbazaar
      POSTGRES_USER: slotbazaar_user
      POSTGRES_PASSWORD: slotbazaar_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slotbazaar_user -d slotbazaar"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - dev

  # Database admin interface
  adminer:
    image: adminer
    container_name: slotbazaar_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    profiles:
      - dev

volumes:
  postgres_data: