version: '3.8'

services:
  # FastAPI Application with SQLite (default)
  app:
    build: .
    container_name: slotbazaar_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Creating database tables...' &&
        python -c 'from app.db import engine; from app.models.base import Base; from app.models.user import User; from app.models.game_session import GameSession; from app.models.transaction import Transaction; Base.metadata.create_all(bind=engine)' &&
        echo 'Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
      
  # Frontend React application
  frontend:
    build: ./slotbazaar-frontend
    container_name: slotbazaar_frontend
    ports:
      - "3000:80"
    depends_on:
      - app

  # FastAPI Application with PostgreSQL
  app-postgres:
    build: .
    container_name: slotbazaar_app_postgres
    environment:
      - DATABASE_URL=postgresql://slotbazaar_user:slotbazaar_password@db:5432/slotbazaar
      - JWT_SECRET_KEY=slotbazaar-postgres-secret-key-2024
      - DEBUG=True
      - ENVIRONMENT=production
    ports:
      - "8004:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python -c 'import time; time.sleep(10)' &&
        echo 'Running migrations...' &&
        alembic upgrade head &&
        echo 'Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    profiles:
      - postgres

  # Development setup with local PostgreSQL (optional)
  app-dev:
    build: .
    container_name: slotbazaar_app_dev
    environment:
      - DATABASE_URL=postgresql://slotbazaar_user:slotbazaar_password@db:5432/slotbazaar
      - JWT_SECRET_KEY=dev-secret-key
      - DEBUG=True
    ports:
      - "8002:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python -c 'import time; time.sleep(5)' &&
        echo 'Running migrations...' &&
        alembic upgrade head &&
        echo 'Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    profiles:
      - dev

  # Local PostgreSQL for development
  db:
    image: postgres:15-alpine
    container_name: slotbazaar_db
    environment:
      POSTGRES_DB: slotbazaar
      POSTGRES_USER: slotbazaar_user
      POSTGRES_PASSWORD: slotbazaar_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slotbazaar_user -d slotbazaar"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - postgres

  # Database admin interface
  adminer:
    image: adminer
    container_name: slotbazaar_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    profiles:
      - postgres

volumes:
  postgres_data: