from .coin_flip import CoinFlipResult
from .dice_roll import DiceRollResult
from .number_guess import NumberGuessResult
from .rock_paper_scissors import RPSResult
from .simplified_blackjack import BlackjackResult
from .simple_roulette import RouletteResult
from .scratch_card import ScratchCardResult
from .high_low_card import HighLowResult
from .three_reel_slot import SlotResult
from .wheel_of_fortune import WheelResult